### ISSUE TITLE
More links to other design resources in gov

### ISSUE THREAD

**Issue by ignaciaorellana** [ctdesign/gov-design-systems-list#1]
Hi Chris,

I've started to collect these resources across government some time ago, here are the links (I hope it's useful) :

## Pattern libraries/Design Systems
CJSCPP Design patterns
https://cjscpp-design-patterns.herokuapp.com/

DWP Design examples (GitHub repo)
https://github.com/dwp/design-examples

DWP Design patterns
https://dwp-patterns.herokuapp.com/

DWP Design patterns (GitHub repo)
https://github.com/dwp/dwp-design

Digital Marketplace frontend toolkit
http://alphagov.github.io/digitalmarketplace-frontend-toolkit/

DVSA Frontend style guide 
https://dvsa-front-end.herokuapp.com/

DVSA Frontend (GitHub repo)
https://github.com/dvsa/front-end

HMRC Design System 
http://hmrc.github.io/assets-frontend/

HMRC Design System (GitHub repo)
https://github.com/hmrc/design-patterns

HMCTS - Reform Pattern library
https://reform-pattern-library.herokuapp.com/

Home Office Design system
https://home-office-digital-patterns.herokuapp.com/patterns

Home Office Design system (GitHub repo)
https://github.com/UKHomeOffice/design-system?files=1

GOV.UK Publishing components - component guide
https://govuk-publishing-components.herokuapp.com/component-guide

GOV.UK Publishing components - component guide (GitHub repo)
https://github.com/alphagov/govuk_publishing_components

Land Registry elements
http://land-registry-elements.herokuapp.com/

Land Registry elements (GitHub repo)
https://github.com/LandRegistry/land-registry-elements

Rural Payments style guide 
http://rural-payments-styleguide.herokuapp.com/

Skills Funding Agency
https://github.com/SkillsFundingAgency/esfa-pattern-library

## Design resources
DEFRA Form Builder
https://digital-form-builder.herokuapp.com/split 

HOF - Home Office Form builder
https://ukhomeofficeforms.github.io/hof-guide/

**Comment by NickColley** [comment]
You could replace the GOV.UK Publishing guide with https://docs.publishing.service.gov.uk/manual/components.html#component-guides

**Comment by ctdesign** [comment]
Thanks both - I've updated my list now. A few of the things had changed and some I couldnt access because of authentication.

**Comment by EdoPlantinga** [comment]
Hi CTdesig, 
Edo Plantinga speaking, working for a joint design system for Dutch gov. You may also be interested in this overview: https://clarity.codefor.nl/cbase/patroonbibliotheken-40d645ed91dcf7bacb55f1a5d7b5abc0 
Best regards,

Edo
Twitter: @edoplantinga
