### ISSUE TITLE
Idea to expose pattern libraries and encourage reuse...

### ISSUE THREAD

**Issue by adamsilver** [ctdesign/gov-design-systems-list#2]
What if this list was stored as JSON and released as an NPM package?

```
{ "govdesignsystems": [{ 
    name: "HMCTS Design System", 
    "url: "https://hmcts-design-system.herokuapp.com" 
}, ...] }
```

I was thinking other government design systems could pull it in and reference it somewhere easily in theirs. Perhaps, even the GOV.UK Design System could do the same somewhere.

**Comment by ctdesign** [comment]
Sorry mate - didnt spot this - this is a great idea, I'll look at sorting something.
